default: &default
  adapter: postgresql
  checkout_timeout: <%= Integer(ENV.fetch('DATABASE_TIMEOUT', 1)) %>
  connect_timeout: <%= Integer(ENV.fetch('DATABASE_TIMEOUT', 1)) %>
  encoding: unicode
  pool: <%= Integer(ENV.fetch('RAILS_MAX_THREADS', 5)) %>
  prepared_statements: false
  url: <%= ENV.fetch('DATABASE_URL') %>
  variables:
    statement_timeout: <%= Integer(ENV.fetch('DATABASE_TIMEOUT', 1)) * 1000 %>

development:
  <<: *default

test:
  <<: *default
  url: <%= "#{ENV.fetch('DATABASE_URL')}#{ENV['TEST_ENV_NUMBER']}" %>

production:
  <<: *default
